name: migran
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  get: ^4.6.5
  flutter_date_pickers: ^0.4.0
  flutter_linear_datepicker: ^2.0.4
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg
